In [1]:
# 텐서 연산 및 차원 조작
import torch

In [2]:
# 길이가 3인 벡터 두 개 생성
v = torch.tensor([1, 2, 3]) 
w = torch.tensor([3, 4, 6])
print(w - v) # 길이가 같은 벡터 간 뺄셈 연산

tensor([2, 2, 3])


In [3]:
temp = torch.tensor([[1, 2], [3, 4]]) # 2 x 2 행렬 생성

print(temp.shape)
print("-----------------------")
print(temp.view(4, 1)) # 2 x 2 행렬을 4 x 1로 변형
print("-----------------------")
print(temp.view(-1)) # 2 x 2 행렬을 1차원 벡터로 변형
print("-----------------------")
# -1은 (1, ?)와 같은 의미로 다른 차원으로부터 해당 값을 유추하겠다는 것입니다.
# temp의 원소 개수(2x2=4)를 유지한 채 (1, ?)를 만족해야 하므로 (1, 4)가 된다.
print(temp.view(1, -1))
print("-----------------------")
print(temp.view(-1, 1)) # 앞에서 마찬가지로 temp의 원소 개수를 만족하며 (?, 1) 형태를 유지해야 하므로 (4, 1)이 된다.

torch.Size([2, 2])
-----------------------
tensor([[1],
        [2],
        [3],
        [4]])
-----------------------
tensor([1, 2, 3, 4])
-----------------------
tensor([[1, 2, 3, 4]])
-----------------------
tensor([[1],
        [2],
        [3],
        [4]])
