In [ ]:
# 해당 코드는 numpy 메서드인 numpy.stack과 numpyconcatenate의 차이점을 보여주는 코드다.

# 넘파이 객체를 합칠 때 사용하는 메서드로는 np.stack과 np.caoncatenate가 있다.
# 이 두 메서드는 차원의 유지 여부에 대한 차이가 있다.

In [9]:
import numpy as np

# 같은 형태의 배열 2개, 다른 형태의 배열 1개, 다른 차원의 배열 1개 선언
a = np.array([[1,2],[3,4]]) # a.shape = (2, 2)
b = np.array([[5,6],[7,8]]) # b.shape = (2, 2)
c = np.array([[5,6],[7,8],[9,10]]) # c.shape = (3, 2)
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # d.shape = (2, 2, 2)

In [18]:
# np.concatenate() 메서드는 axis(0: 세로축, 1: 가로축)를 기준으로 배열을 합친다.
print(np.concatenate((a, b), axis=0)) # shape = (4, 2)
print("-----------------------------")
print(np.concatenate((a, b), axis=1)) # shape = (2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-----------------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [22]:
# 또 np.concatenate는 배열의 형태가 달라도 합칠 수 있다.
print(np.concatenate((a, c), axis=0)) # shape = (5, 2)
print("-----------------------------")
# 단, 배열의 형태가 다르되 축 기준의 요소의 수는 같아야 된다.
print(np.concatenate((a, c), axis=1))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
-----------------------------


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
# 당연한 애기지만 서로 차원이 다르면 에러가 발생한다.

In [7]:
# 반면 np.stack() 메서드는 배열들을 새로운 상위 차원의 배열로 합친다.
# 예를 들어, 2차원 배열들을 합친다 가정하면 3차원 배열이 생성된다.
print(np.stack((a, b), axis=0))
print("-----------------------------")
print(np.stack((a, b), axis=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-----------------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [24]:
# np.concatenate() 메서드와 다르게 형태가 같아야 된다.
# 형태가 다르면 오류가 발생한다.
print(np.stack((a, c), axis=0))

ValueError: all input arrays must have the same shape

In [31]:
# 당연한 애기지만 두 메서드 모두 차원이 다르면 오류가 발생한다.
try:
    print(np.concatenate((a, d), axis=0))
except Exception as e:
    print(e)

try:
    print(np.stack((a, d), axis=0))
except Exception as e:
    print(e)

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)
all input arrays must have the same shape
