In [1]:
# ravel(), reshape(), faltten()은 텐서의 차원을 바꿀 때 사용합니다.

In [2]:
import numpy as np

In [3]:
# numpy 배열 생성
a = np.array([[1, 2],
              [3, 4]])

In [5]:
# 실행하면 2차원에서 1차원으로 배열이 변경되어 출력된다.
print(a.ravel())
print(a.reshape(-1))
print(a.flatten())

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
